services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/media-service-example"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    dns:
      - 77.88.8.8
      - 77.88.8.1
    network_mode: host
#    command: ["fastapi", "run", "src/app.py", "--proxy-headers", "--host", "localhost", "--port", "80"]
    command: ["uvicorn", "src.app:app"]

  db:
    image: postgres:16.8-bullseye
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: sh -c "pg_isready -U ${POSTGRES_USER} -h localhost"
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - custom
    volumes:
      - media-service-example:/var/lib/postgresql/data
volumes:
  media-service-example:
networks:
  custom:
    driver: bridge
